timesheet_token/force-app/main/default/objects/Contact/fields/Form_Filled__c.field-meta.xml
<CustomField>
    <fullName>Form_Filled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Form Filled</label>
    <type>Checkbox</type>
</CustomField>

timesheet_token/force-app/main/default/objects/Contact/fields/MD5_Token__c.field-meta.xml
<CustomField>
    <fullName>MD5_Token__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>MD5 Token</label>
    <length>32</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

timesheet_token/force-app/main/default/classes/DailyEmailScheduler.cls
global class DailyEmailScheduler implements Schedulable {
    global void execute(SchedulableContext sc) {
        sendEmails();
    }

    public void sendEmails() {
        List<Contact> contacts = [SELECT Id, FirstName, LastName, Email, MD5_Token__c, Form_Filled__c FROM Contact WHERE Form_Filled__c = false AND Employee__c = true];
        Id templateId = '00XQy000001UAvp';
        for (Contact contact : contacts) {
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setTargetObjectId(contact.Id);
            mail.setTemplateId(templateId);
            mail.setSaveAsActivity(false);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});
        }
    }

    global static void scheduleJob() {
        String cronExp = '0 30 16 * * ?'; // Runs @ 16:30 every day
        String jobName = 'DailyEmailJob';
        System.schedule(jobName, cronExp, new DailyEmailScheduler());
    }
}