timesheet_token/force-app/main/default/objects/Contact/fields/Form_Filled__c.field-meta.xml
<CustomField>
    <fullName>Form_Filled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Form Filled</label>
    <type>Checkbox</type>
</CustomField>

timesheet_token/force-app/main/default/objects/Contact/fields/MD5_Token__c.field-meta.xml
<CustomField>
    <fullName>MD5_Token__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>MD5 Token</label>
    <length>32</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

timesheet_token/force-app/main/default/objects/Timesheet__c/Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <label>Timesheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

timesheet_token/force-app/main/default/objects/Timesheet__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

timesheet_token/force-app/main/default/objects/Timesheet_Project__c/Timesheet_Project__c.object-meta.xml
<CustomObject>
    <label>Timesheet Project</label>
    <nameField>
        <label>Timesheet Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Timesheet Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

timesheet_token/force-app/main/default/objects/Timesheet_Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Timesheet Projects</relationshipLabel>
    <relationshipName>Timesheet_Projects</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

timesheet_token/force-app/main/default/objects/Timesheet_Project__c/fields/Timesheet__c.field-meta.xml
<CustomField>
    <fullName>Timesheet__c</fullName>
    <label>Timesheet</label>
    <referenceTo>Timesheet__c</referenceTo>
    <relationshipLabel>Timesheet Projects</relationshipLabel>
    <relationshipName>Timesheet_Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

timesheet_token/force-app/main/default/classes/TimesheetController.cls
public class TimesheetController {
    public Timesheet__c timesheet { get; set; }
    public Contact contact { get; set; }
    public List<ProjectWrapper> projects { get; set; }

    public TimesheetController() {
        String md5Token = ApexPages.currentPage().getParameters().get('md5Token');
        contact = [SELECT Id, FirstName, LastName, Form_Filled__c FROM Contact WHERE MD5_Token__c = :md5Token LIMIT 1];

        timesheet = new Timesheet__c();
        timesheet.Employee__c = contact.Id;

        projects = new List<ProjectWrapper>();
        for (Project__c project : [SELECT Id, Name FROM Project__c]) {
            projects.add(new ProjectWrapper(project));
        }
    }

    public class ProjectWrapper {
        public Project__c project { get; set; }
        public Boolean selected { get; set; }

        public ProjectWrapper(Project__c project) {
            this.project = project;
            this.selected = false;
        }
    }

    public PageReference submitForm() {
        insert timesheet;
        for (ProjectWrapper wrapper : projects) {
            if (wrapper.selected) {
                Timesheet_Project__c junction = new Timesheet_Project__c();
                junction.Timesheet__c = timesheet.Id;
                junction.Project__c = wrapper.project.Id;
                insert junction;
            }
        }
        contact.Form_Filled__c = true;
        update contact;
        return Page.ReportFormCompleted;
    }
}